### ISSUE TITLE
End of data reached ... Corrupted zip ?

### ISSUE THREAD

**Issue by dvdobrovolskiy** [Stuk/jszip#511]
Attaching file created by JSZip 
Cannot unzip by JSZip 

[database (10).zip](https://github.com/Stuk/jszip/files/1845971/database.10.zip)

jszip.min.js:12 Uncaught (in promise) Error: End of data reached (data length = 108213, asked index = 108214). Corrupted zip ?
    at d.checkIndex (jszip.min.js:12)
    at d.checkOffset (jszip.min.js:12)
    at d.readInt (jszip.min.js:12)
    at d.readBlockEndOfCentral (jszip.min.js:13)
    at d.readEndOfCentral (jszip.min.js:13)
    at d.load (jszip.min.js:13)
    at jszip.min.js:12

**Comment by vicky8989** [comment]
i had the same error..

**Comment by nitinmagdumvista** [comment]
error reading zip Error: End of data reached (data length = 4290048, asked index = 4338619). Corrupted zip ?
    at NodeBufferReader.checkIndex (/Users/nitinshamaravmagdum/Documents/Project_List/logos-service/node_modules/jszip/lib/reader/DataReader.js:26:19)
    at NodeBufferReader.checkOffset (/Users/nitinshamaravmagdum/Documents/Project_List/logos-service/node_modules/jszip/lib/reader/DataReader.js:17:14)
    at NodeBufferReader.readData (/Users/nitinshamaravmagdum/Documents/Project_List/logos-service/node_modules/jszip/lib/reader/NodeBufferReader.js:14:10)
    at ZipEntries.readBlockEndOfCentral (/Users/nitinshamaravmagdum/Documents/Project_List/logos-service/node_modules/jszip/lib/zipEntries.js:59:38)
    at ZipEntries.readEndOfCentral (/Users/nitinshamaravmagdum/Documents/Project_List/logos-service/node_modules/jszip/lib/zipEntries.js:177:14)
    at ZipEntries.load (/Users/nitinshamaravmagdum/Documents/Project_List/logos-service/node_modules/jszip[[?1;2c24m/lib/zipEntries.js:255:14)
    at /Users/nitinshamaravmagdum/Documents/Project_List/logos-service/node_modules/jszip/lib/load.js:48:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
