### ISSUE TITLE
Error: Corrupted zip: missing 59141 bytes.

### ISSUE THREAD

**Issue by tommedema** [Stuk/jszip#574]
The following simple snippet:

```
import rp from 'request-promise-native'
import zip from 'jszip'

const csvZip = (await rp(csvUrl))
const data = await zip.loadAsync(csvZip)
console.log(data)
```

Results in:

```
Error: Corrupted zip: missing 59141 bytes.
    at ZipEntries.readEndOfCentral (/Users/tommedema/projects/prj/node_modules/jszip/lib/zipEntries.js:244:19)
    at ZipEntries.load (/Users/tommedema/projects/prj/node_modules/jszip/lib/zipEntries.js:256:14)
    at /Users/tommedema/projects/prj/node_modules/jszip/lib/load.js:49:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Is this a known error?

Note that the file unzips just fine on OSX's Archive Utility.

**Comment by tommedema** [comment]
I had searched the docs before but couldn't find a solution.

Now I can: https://stuk.github.io/jszip/documentation/howto/read_zip.html

```
const csvZip = (await rp(csvUrl, { encoding: null }))
```
