### ISSUE TITLE
RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid

### ISSUE THREAD

**Issue by sojwil** [Stuk/jszip#765]
I am using [application](https://github.com/Kentico/kontent-backup-manager-js) which has a reference to jszip.
I opened an [issue](https://github.com/Kentico/kontent-backup-manager-js/issues/17) there, but no luck

At the "Create zip file" stage following error occurs:

There was an error processing your request: RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 4620737532
at Function.allocUnsafe (node:buffer:374:3)
at Function.concat (node:buffer:553:25)
at concat (/usr/lib/node_modules/@kentico/kontent-backup-manager/node_modules/jszip/lib/stream/StreamHelper.js:62:27)
at StreamHelper. (/usr/lib/node_modules/@kentico/kontent-backup-manager/node_modules/jszip/lib/stream/StreamHelper.js:96:61)
at Immediate._onImmediate (/usr/lib/node_modules/@kentico/kontent-backup-manager/node_modules/jszip/lib/utils.js:381:18)
at processImmediate (node:internal/timers:464:21) {
code: 'ERR_INVALID_ARG_VALUE'
}

This looks like a JSZip related issue, although size is not a known restriction.

Zip to be written: 4.6GB
Diskspace: 230GB
Versions used:
Ubuntu 20.04 (In Docker)
Node: v16.1.0
npm: 7.11.2
jszip: 3.6.0

Any help is very welcome

**Comment by 101arrowz** [comment]
This is a physical limitation of JavaScript. It's not really a good idea (or possible for that matter in JavaScript) to allocate 4GB of memory, which is needed for writing the Zip file without streaming. Try using the streaming version of the JSZip exports.
